# Generated by Django 5.2.9 on 2026-03-23 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_head', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoanHead',
        ),
    ]
