# Generated by Django 5.2.9 on 2026-03-05 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_loanapplication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoanApplication',
        ),
    ]
