# Generated by Django 5.2.9 on 2026-03-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_delete_loanapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='bank',
            field=models.CharField(default='SBI', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='mobile',
            field=models.CharField(default='Unknown', max_length=15),
            preserve_default=False,
        ),
    ]
