# Generated by Django 5.2.9 on 2026-03-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_loan_bank_loan_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='loan',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
