# Generated by Django 5.2.9 on 2026-03-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_loan_email_loan_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.AddField(
            model_name='document',
            name='aadhaar_card',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='document',
            name='address_proof',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='document',
            name='bank_statement',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='document',
            name='business_proof',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='document',
            name='income_proof',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='document',
            name='pan_card',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='document',
            name='photo',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='document',
            name='property_document',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='document',
            name='salary_slip',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='document',
            name='signature',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
