# Generated by Django 5.2.9 on 2026-03-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_remove_document_document_type_remove_document_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='aadhaar_card',
        ),
        migrations.RemoveField(
            model_name='document',
            name='address_proof',
        ),
        migrations.RemoveField(
            model_name='document',
            name='bank_statement',
        ),
        migrations.RemoveField(
            model_name='document',
            name='business_proof',
        ),
        migrations.RemoveField(
            model_name='document',
            name='income_proof',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pan_card',
        ),
        migrations.RemoveField(
            model_name='document',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='document',
            name='property_document',
        ),
        migrations.RemoveField(
            model_name='document',
            name='salary_slip',
        ),
        migrations.RemoveField(
            model_name='document',
            name='signature',
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
