# Generated by Django 5.2.9 on 2026-03-23 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_remove_loanhead_description_loanhead_email_and_more'),
        ('customer', '0009_document_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.loanhead'),
        ),
    ]
