# Generated by Django 5.2.9 on 2026-03-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanhead',
            name='description',
        ),
        migrations.AddField(
            model_name='loanhead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='loanhead',
            name='password',
            field=models.CharField(default='test@gmail.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanhead',
            name='phone',
            field=models.CharField(default='test123', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loanhead',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
